on:
  [pull_request]
  
name: Jira Check

jobs:
  test-find-issue-key:
    name: Find Issue Key
    runs-on: ubuntu-latest
    
    steps:
    - name: Debug Action
      uses: hmarr/debug-action@v1.0.0
            
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      
    - name: Get Issue Key
      id: find
      uses: sunil-bansiwal/find-jira-issue@master
      with:
        from: pullRequest
           
    - name: Find issue info
      run: echo "Issue ${{ steps.find.outputs.issue }} was found"
    

