on:
  [push]
  
name: Jira Check

jobs:
  test-find-issue-key:
    name: Find Issue Key
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Find Issue Key
      id: find
      uses: sunil-bansiwal/find-jira-issue@master
      with:
        from: commits

    - name: Find issue info
      run: echo "Issue ${{ steps.find.outputs.issue }} was found"
